<?php $form->prepare();?>

<?php echo $this->form()->openTag($form);?>

<?php foreach ($form as $element):?>
    <?php $error = (boolean) count($element->getMessages()); ?>

    <div class="form-group <?php if($error):?>has-error has-feedback<?php endif;?>">
        <label class="col-sm-2 control-label" for="<?php echo $element->getName();?>">
            <?php echo $element->getLabel() ?>
        </label>
        <div class='col-sm-10'>
            <?php echo $this->formElement($element);?>
            <?php if ($error): ?>
                <?php echo $this->formElementErrors($element,array('class' => 'errors')) ?>
            <?php endif;?>
        </div>
    </div>

<?php endforeach; ?>

    <div class="clear"></div>

    <div class="form-group">
        <div class='col-sm-offset-2 col-sm-10'>
            <input type="submit" value="Send" class="btn btn-large btn-primary"/>
        </div>
    </div>

<?php echo $this->form()->closeTag();?>