<table class="table table-striped table-responsive table-condensed table-hover">
    <thead>
    <tr>
        <th class="span1">Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Birthday</th>
        <th>Level</th>
    </tr>
    </thead>

    <?php foreach($this->items as $item) : ?>
        <tr>
            <td><?php echo $item->id; ?></td>
            <td><?php echo $item->name; ?></td>
            <td><?php echo $item->email; ?></td>
            <td><?php echo $item->birthday; ?></td>
            <td><?php echo $item->level; ?></td>
        </tr>
    <?php endforeach; ?>

</table>