<table class="table table-striped table-responsive table-condensed table-hover">
    <thead>
    <tr>
        <th class="span1">Id</th>
        <th>Name</th>
        <th>Email</th>
        <th>Birthday</th>
        <th>Level</th>
    </tr>
    </thead>

    <?php foreach($this->items as $item) : ?>
        <tr>
            <td><?php echo $item->getId(); ?></td>
            <td><?php echo $item->getName(); ?></td>
            <td><?php echo $item->getEmail(); ?></td>
            <td><?php echo $item->getBirthday(); ?></td>
            <td><?php echo $item->getLevel(); ?></td>
        </tr>
    <?php endforeach; ?>

</table>