<table class="table table-striped table-responsive table-condensed table-hover">
    <thead>
    <tr>
        <th class="span1">Id</th>
        <th>Name</th>
        <th>Gender</th>
        <th>Phone</th>
        <?php if ($this->pupils): ?>
            <th>Count of pupils</th>
        <?php endif;?>
    </tr>
    </thead>

    <?php foreach($this->items as $item) : ?>
        <tr>
            <td><?php echo $item->id; ?></td>
            <td>
                <a href="<?php echo $this->url('teacher_assign', ['id' => $item->id]);?>">
                    <?php echo $item->name; ?>
                </a>
            </td>
            <td><?php echo $item->getGender(); ?></td>
            <td><?php echo $item->phone; ?></td>
            <?php if ($this->pupils): ?>
                <td><?php echo $this->pupils[$item->id]; ?></td>
            <?php endif;?>
        </tr>
    <?php endforeach; ?>

</table>